INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_0');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_1');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_2');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_3');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_4');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_5');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_6');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_7');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_8');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_9');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_10');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_11');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_12');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_13');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_14');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_15');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_16');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_17');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_18');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_19');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_20');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_21');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_22');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_23');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_24');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_25');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_26');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_27');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_28');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_29');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_30');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_31');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_32');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_33');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_34');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_35');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_36');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_37');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_38');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_39');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_40');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_41');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_42');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_43');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_44');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_45');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_46');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_47');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_48');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_49');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_50');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_51');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_52');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_53');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_54');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_55');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_56');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_57');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_58');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_59');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_60');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_61');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_62');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_63');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_64');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_65');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_66');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_67');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_68');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_69');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_70');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_71');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_72');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_73');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_74');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_75');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_76');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_77');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_78');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_79');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_80');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_81');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_82');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_83');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_84');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_85');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_86');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_87');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_88');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_89');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_90');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_91');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_92');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_93');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_94');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_95');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_96');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_97');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_98');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_99');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_100');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_101');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_102');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_103');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_104');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_105');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_106');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_107');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_108');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_109');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_110');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_111');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_112');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_113');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_114');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_115');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_116');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_117');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_118');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_119');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_120');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_121');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_122');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_123');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_124');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_125');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_126');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_127');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_128');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_129');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_130');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_131');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_132');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_133');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_134');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_135');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_136');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_137');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_138');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_139');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_140');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_141');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_142');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_143');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_144');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_145');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_146');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_147');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_148');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_149');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_150');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_151');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_152');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_153');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_154');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_155');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_156');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_157');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_158');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_159');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_160');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_161');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_162');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_163');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_164');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_165');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_166');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_167');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_168');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_169');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_170');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_171');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_172');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_173');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_174');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_175');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_176');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_177');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_178');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_179');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_180');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_181');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_182');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_183');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_184');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_185');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_186');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_187');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_188');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_189');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_190');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_191');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_192');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_193');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_194');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_195');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_196');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_197');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_198');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_199');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_200');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_201');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_202');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_203');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_204');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_205');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_206');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_207');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_208');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_209');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_210');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_211');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_212');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_213');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_214');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_215');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_216');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_217');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_218');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_219');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_220');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_221');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_222');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_223');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_224');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_225');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_226');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_227');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_228');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_229');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_230');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_231');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_232');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_233');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_234');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_235');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_236');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_237');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_238');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_239');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_240');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_241');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_242');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_243');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_244');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_245');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_246');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_247');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_248');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_249');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_250');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_251');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_252');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_253');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_254');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_255');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_256');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_257');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_258');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_259');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_260');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_261');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_262');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_263');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_264');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_265');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_266');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_267');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_268');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_269');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_270');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_271');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_272');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_273');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_274');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_275');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_276');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_277');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_278');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_279');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_280');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_281');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_282');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_283');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_284');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_285');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_286');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_287');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_288');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_289');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_290');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_291');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_292');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_293');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_294');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_295');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_296');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_297');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_298');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_299');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_300');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_301');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_302');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_303');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_304');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_305');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_306');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_307');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_308');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_309');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_310');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_311');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_312');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_313');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_314');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_315');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_316');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_317');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_318');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_319');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_320');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_321');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_322');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_323');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_324');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_325');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_326');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_327');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_328');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_329');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_330');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_331');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_332');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_333');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_334');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_335');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_336');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_337');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_338');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_339');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_340');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_341');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_342');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_343');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_344');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_345');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_346');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_347');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_348');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_349');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_350');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_351');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_352');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_353');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_354');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_355');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_356');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_357');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_358');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_359');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_360');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_361');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_362');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_363');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_364');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_365');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_366');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_367');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_368');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_369');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_370');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_371');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_372');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_373');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_374');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_375');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_376');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_377');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_378');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_379');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_380');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_381');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_382');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_383');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_384');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_385');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_386');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_387');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_388');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_389');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_390');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_391');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_392');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_393');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_394');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_395');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_396');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_397');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_398');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_399');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_400');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_401');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_402');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_403');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_404');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_405');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_406');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_407');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_408');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_409');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_410');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_411');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_412');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_413');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_414');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_415');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_416');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_417');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_418');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_419');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_420');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_421');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_422');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_423');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_424');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_425');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_426');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_427');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_428');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_429');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_430');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_431');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_432');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_433');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_434');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_435');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_436');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_437');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_438');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_439');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_440');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_441');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_442');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_443');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_444');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_445');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_446');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_447');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_448');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_449');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_450');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_451');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_452');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_453');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_454');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_455');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_456');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_457');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_458');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_459');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_460');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_461');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_462');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_463');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_464');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_465');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_466');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_467');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_468');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_469');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_470');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_471');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_472');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_473');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_474');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_475');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_476');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_477');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_478');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_479');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_480');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_481');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_482');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_483');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_484');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_485');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_486');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_487');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_488');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_489');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_490');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_491');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_492');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_493');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_494');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_495');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_496');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_497');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_498');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_499');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_500');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_501');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_502');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_503');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_504');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_505');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_506');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_507');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_508');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_509');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_510');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_511');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_512');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_513');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_514');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_515');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_516');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_517');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_518');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_519');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_520');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_521');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_522');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_523');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_524');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_525');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_526');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_527');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_528');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_529');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_530');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_531');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_532');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_533');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_534');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_535');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_536');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_537');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_538');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_539');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_540');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_541');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_542');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_543');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_544');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_545');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_546');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_547');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_548');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_549');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_550');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_551');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_552');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_553');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_554');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_555');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_556');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_557');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_558');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_559');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_560');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_561');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_562');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_563');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_564');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_565');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_566');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_567');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_568');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_569');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_570');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_571');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_572');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_573');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_574');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_575');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_576');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_577');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_578');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_579');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_580');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_581');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_582');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_583');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_584');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_585');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_586');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_587');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_588');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_589');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_590');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_591');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_592');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_593');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_594');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_595');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_596');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_597');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_598');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_599');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_600');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_601');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_602');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_603');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_604');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_605');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_606');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_607');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_608');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_609');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_610');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_611');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_612');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_613');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_614');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_615');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_616');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_617');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_618');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_619');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_620');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_621');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_622');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_623');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_624');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_625');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_626');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_627');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_628');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_629');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_630');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_631');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_632');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_633');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_634');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_635');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_636');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_637');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_638');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_639');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_640');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_641');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_642');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_643');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_644');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_645');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_646');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_647');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_648');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_649');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_650');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_651');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_652');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_653');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_654');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_655');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_656');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_657');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_658');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_659');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_660');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_661');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_662');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_663');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_664');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_665');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_666');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_667');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_668');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_669');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_670');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_671');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_672');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_673');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_674');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_675');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_676');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_677');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_678');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_679');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_680');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_681');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_682');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_683');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_684');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_685');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_686');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_687');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_688');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_689');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_690');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_691');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_692');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_693');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_694');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_695');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_696');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_697');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_698');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_699');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_700');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_701');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_702');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_703');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_704');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_705');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_706');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_707');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_708');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_709');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_710');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_711');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_712');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_713');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_714');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_715');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_716');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_717');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_718');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_719');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_720');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_721');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_722');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_723');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_724');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_725');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_726');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_727');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_728');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_729');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_730');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_731');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_732');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_733');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_734');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_735');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_736');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_737');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_738');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_739');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_740');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_741');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_742');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_743');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_744');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_745');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_746');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_747');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_748');
INSERT INTO treatments
VALUES (DEFAULT, 'treatment_name_749');
