INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_0');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_1');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_2');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_3');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_4');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_5');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_6');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_7');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_8');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_9');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_10');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_11');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_12');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_13');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_14');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_15');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_16');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_17');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_18');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_19');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_20');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_21');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_22');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_23');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_24');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_25');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_26');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_27');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_28');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_29');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_30');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_31');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_32');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_33');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_34');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_35');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_36');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_37');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_38');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_39');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_40');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_41');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_42');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_43');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_44');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_45');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_46');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_47');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_48');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_49');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_50');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_51');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_52');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_53');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_54');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_55');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_56');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_57');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_58');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_59');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_60');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_61');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_62');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_63');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_64');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_65');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_66');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_67');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_68');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_69');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_70');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_71');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_72');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_73');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_74');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_75');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_76');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_77');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_78');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_79');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_80');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_81');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_82');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_83');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_84');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_85');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_86');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_87');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_88');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_89');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_90');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_91');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_92');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_93');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_94');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_95');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_96');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_97');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_98');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_99');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_100');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_101');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_102');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_103');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_104');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_105');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_106');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_107');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_108');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_109');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_110');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_111');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_112');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_113');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_114');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_115');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_116');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_117');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_118');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_119');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_120');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_121');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_122');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_123');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_124');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_125');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_126');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_127');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_128');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_129');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_130');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_131');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_132');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_133');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_134');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_135');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_136');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_137');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_138');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_139');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_140');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_141');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_142');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_143');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_144');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_145');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_146');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_147');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_148');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_149');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_150');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_151');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_152');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_153');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_154');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_155');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_156');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_157');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_158');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_159');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_160');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_161');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_162');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_163');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_164');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_165');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_166');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_167');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_168');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_169');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_170');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_171');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_172');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_173');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_174');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_175');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_176');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_177');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_178');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_179');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_180');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_181');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_182');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_183');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_184');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_185');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_186');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_187');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_188');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_189');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_190');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_191');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_192');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_193');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_194');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_195');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_196');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_197');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_198');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_199');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_200');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_201');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_202');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_203');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_204');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_205');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_206');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_207');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_208');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_209');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_210');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_211');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_212');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_213');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_214');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_215');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_216');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_217');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_218');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_219');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_220');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_221');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_222');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_223');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_224');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_225');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_226');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_227');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_228');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_229');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_230');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_231');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_232');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_233');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_234');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_235');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_236');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_237');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_238');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_239');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_240');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_241');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_242');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_243');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_244');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_245');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_246');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_247');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_248');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_249');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_250');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_251');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_252');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_253');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_254');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_255');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_256');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_257');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_258');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_259');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_260');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_261');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_262');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_263');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_264');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_265');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_266');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_267');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_268');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_269');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_270');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_271');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_272');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_273');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_274');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_275');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_276');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_277');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_278');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_279');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_280');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_281');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_282');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_283');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_284');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_285');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_286');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_287');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_288');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_289');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_290');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_291');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_292');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_293');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_294');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_295');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_296');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_297');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_298');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_299');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_300');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_301');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_302');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_303');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_304');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_305');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_306');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_307');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_308');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_309');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_310');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_311');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_312');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_313');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_314');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_315');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_316');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_317');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_318');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_319');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_320');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_321');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_322');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_323');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_324');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_325');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_326');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_327');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_328');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_329');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_330');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_331');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_332');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_333');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_334');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_335');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_336');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_337');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_338');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_339');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_340');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_341');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_342');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_343');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_344');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_345');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_346');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_347');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_348');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_349');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_350');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_351');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_352');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_353');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_354');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_355');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_356');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_357');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_358');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_359');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_360');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_361');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_362');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_363');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_364');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_365');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_366');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_367');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_368');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_369');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_370');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_371');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_372');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_373');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_374');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_375');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_376');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_377');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_378');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_379');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_380');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_381');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_382');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_383');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_384');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_385');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_386');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_387');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_388');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_389');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_390');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_391');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_392');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_393');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_394');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_395');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_396');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_397');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_398');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_399');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_400');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_401');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_402');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_403');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_404');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_405');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_406');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_407');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_408');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_409');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_410');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_411');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_412');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_413');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_414');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_415');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_416');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_417');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_418');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_419');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_420');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_421');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_422');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_423');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_424');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_425');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_426');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_427');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_428');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_429');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_430');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_431');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_432');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_433');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_434');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_435');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_436');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_437');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_438');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_439');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_440');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_441');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_442');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_443');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_444');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_445');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_446');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_447');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_448');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_449');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_450');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_451');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_452');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_453');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_454');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_455');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_456');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_457');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_458');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_459');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_460');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_461');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_462');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_463');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_464');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_465');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_466');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_467');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_468');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_469');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_470');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_471');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_472');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_473');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_474');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_475');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_476');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_477');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_478');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_479');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_480');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_481');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_482');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_483');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_484');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_485');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_486');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_487');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_488');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_489');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_490');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_491');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_492');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_493');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_494');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_495');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_496');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_497');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_498');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_499');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_500');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_501');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_502');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_503');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_504');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_505');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_506');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_507');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_508');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_509');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_510');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_511');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_512');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_513');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_514');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_515');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_516');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_517');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_518');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_519');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_520');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_521');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_522');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_523');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_524');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_525');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_526');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_527');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_528');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_529');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_530');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_531');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_532');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_533');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_534');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_535');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_536');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_537');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_538');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_539');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_540');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_541');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_542');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_543');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_544');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_545');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_546');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_547');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_548');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_549');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_550');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_551');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_552');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_553');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_554');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_555');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_556');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_557');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_558');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_559');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_560');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_561');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_562');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_563');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_564');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_565');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_566');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_567');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_568');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_569');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_570');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_571');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_572');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_573');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_574');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_575');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_576');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_577');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_578');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_579');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_580');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_581');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_582');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_583');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_584');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_585');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_586');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_587');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_588');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_589');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_590');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_591');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_592');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_593');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_594');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_595');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_596');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_597');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_598');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_599');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_600');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_601');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_602');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_603');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_604');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_605');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_606');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_607');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_608');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_609');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_610');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_611');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_612');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_613');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_614');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_615');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_616');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_617');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_618');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_619');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_620');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_621');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_622');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_623');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_624');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_625');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_626');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_627');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_628');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_629');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_630');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_631');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_632');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_633');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_634');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_635');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_636');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_637');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_638');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_639');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_640');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_641');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_642');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_643');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_644');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_645');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_646');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_647');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_648');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_649');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_650');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_651');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_652');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_653');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_654');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_655');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_656');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_657');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_658');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_659');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_660');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_661');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_662');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_663');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_664');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_665');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_666');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_667');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_668');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_669');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_670');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_671');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_672');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_673');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_674');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_675');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_676');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_677');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_678');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_679');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_680');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_681');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_682');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_683');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_684');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_685');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_686');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_687');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_688');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_689');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_690');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_691');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_692');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_693');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_694');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_695');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_696');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_697');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_698');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_699');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_700');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_701');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_702');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_703');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_704');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_705');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_706');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_707');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_708');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_709');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_710');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_711');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_712');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_713');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_714');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_715');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_716');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_717');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_718');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_719');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_720');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_721');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_722');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_723');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_724');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_725');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_726');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_727');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_728');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_729');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_730');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_731');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_732');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_733');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_734');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_735');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_736');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_737');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_738');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_739');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_740');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_741');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_742');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_743');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_744');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_745');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_746');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_747');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_748');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_749');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_750');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_751');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_752');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_753');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_754');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_755');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_756');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_757');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_758');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_759');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_760');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_761');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_762');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_763');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_764');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_765');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_766');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_767');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_768');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_769');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_770');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_771');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_772');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_773');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_774');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_775');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_776');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_777');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_778');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_779');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_780');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_781');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_782');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_783');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_784');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_785');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_786');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_787');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_788');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_789');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_790');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_791');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_792');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_793');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_794');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_795');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_796');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_797');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_798');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_799');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_800');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_801');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_802');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_803');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_804');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_805');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_806');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_807');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_808');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_809');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_810');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_811');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_812');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_813');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_814');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_815');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_816');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_817');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_818');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_819');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_820');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_821');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_822');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_823');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_824');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_825');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_826');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_827');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_828');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_829');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_830');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_831');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_832');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_833');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_834');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_835');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_836');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_837');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_838');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_839');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_840');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_841');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_842');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_843');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_844');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_845');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_846');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_847');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_848');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_849');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_850');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_851');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_852');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_853');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_854');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_855');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_856');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_857');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_858');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_859');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_860');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_861');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_862');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_863');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_864');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_865');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_866');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_867');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_868');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_869');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_870');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_871');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_872');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_873');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_874');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_875');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_876');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_877');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_878');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_879');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_880');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_881');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_882');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_883');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_884');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_885');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_886');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_887');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_888');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_889');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_890');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_891');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_892');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_893');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_894');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_895');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_896');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_897');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_898');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_899');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_900');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_901');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_902');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_903');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_904');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_905');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_906');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_907');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_908');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_909');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_910');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_911');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_912');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_913');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_914');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_915');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_916');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_917');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_918');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_919');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_920');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_921');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_922');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_923');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_924');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_925');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_926');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_927');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_928');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_929');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_930');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_931');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_932');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_933');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_934');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_935');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_936');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_937');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_938');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_939');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_940');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_941');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_942');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_943');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_944');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_945');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_946');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_947');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_948');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_949');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_950');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_951');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_952');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_953');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_954');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_955');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_956');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_957');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_958');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_959');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_960');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_961');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_962');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_963');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_964');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_965');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_966');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_967');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_968');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_969');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_970');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_971');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_972');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_973');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_974');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_975');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_976');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_977');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_978');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_979');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_980');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_981');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_982');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_983');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_984');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_985');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_986');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_987');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_988');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_989');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_990');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_991');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_992');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_993');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_994');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_995');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_996');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_997');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_998');
INSERT INTO illnesses
VALUES (DEFAULT, 'illness_name_999');
